### PR TITLE
correctly handle backwards seeking, fix for #40

### PR DESCRIPTION
**Pull request by evanrichter**
I also added an overflow check for positive seek offsets, because I am thinking that should be caught as an error. Even though seeking past the end of a file is allowed, seeking so far as integer overflow is likely not a good program behavior. I could _maybe_ see using `saturating_add` instead, but I'll let you decide on that.

I would like to add tests that cover both positive and negative seeking from `Current` and `End`, but the tests aren't working for me currently, so I don't have confidence to write good tests at this time

Overall, I tried to not repeat code or be too obtuse in my changes, but let me know if the style is not clear or you want any other change while the pr is open, I'd be happy to do so.

### CODE REVIEW

**Comment by withoutboats** [comment]
This is great! The only nit is that `lseek` does not return `EINVAL` when you overflow the offset, it returns `EOVERFLOW`, so I think we should do that as well. Unfortunately there's no error kind for EOVERFLOW, but you can construct this error with:

```rust
io::Error::from_raw_os_error(libc::EOVERFLOW)
```

**Comment by evanrichter** [comment]
Ok I think it should be set now, good catch for the overflow being a different error

**Comment by withoutboats** [comment]
Thanks, this looks great!

**Comment by evanrichter** [comment]
No problem, glad to help!

**Pull request merged**
